apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: tasks-app
spec:
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: akifbatur/users-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
