apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: tasks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: akifbatur/auth-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
