apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: tasks-app
spec:
  selector:
    app: auth-api
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000
