apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api
  namespace: tasks-app
spec:
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      containers:
      - name: tasks-api
        image: akifbatur/tasks-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
